# Generated by Django 2.0.1 on 2018-12-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0029_auto_20181118_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnode',
            name='created_date',
            field=models.CharField(default='2018-12-07', max_length=50),
        ),
        migrations.AddField(
            model_name='classnode',
            name='founder_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='classnode',
            name='image',
            field=models.ImageField(default='classImg/LYAN1.jpg', upload_to='classImg/'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-12-07 03:54:35', max_length=50),
        ),
    ]
