# Generated by Django 2.1.4 on 2018-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0030_auto_20181207_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-12-26 05:28:15', max_length=50),
        ),
        migrations.AlterField(
            model_name='classnode',
            name='created_date',
            field=models.CharField(default='2018-12-26', max_length=50),
        ),
    ]
